---
title: the Cross Orlando
timezone: UTC
collections:
  messages:
    title: Messages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: messages
  values:
    layout: message
    permalink: "/messages/:year/:month/:day/"
description: The Cross Orlando is a congregation of people living under the reign
  of God. We gather together regularly, we're working in all sectors of our city and
  are always looking for ways to better care for each other.
url: https://thecrossorlando.github.io
keywords: christian, gospel, church
markdown: kramdown
podcast_author: Ben Hoyer
podcast_email: ben@thehoyers.com
