---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: " "
collections: 
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
