---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: sections
  label: Sections
  type: field_group_list
  fields:
  - name: title
    label: Title
    type: text
    hidden: false
    default: ''
  - name: image
    label: Image
    type: file
    hidden: false
    default: ''
  - name: body
    label: Body
    type: textarea
    hidden: false
    default: ''
  hidden: false
  default: ''
pages:
- values.html
- care.html
- gatherings.html
